require 'active_record/fixtures'

class ImportInitialData < ActiveRecord::Migration
  def self.up

    Fixtures.create_fixtures('test/fixtures', :m_users)
    Fixtures.create_fixtures('test/fixtures', :m_user_attributes)
    user_attributes_update_sql = Array.new

    Fixtures.create_fixtures('test/fixtures', :m_user_belongs)
    Fixtures.create_fixtures('test/fixtures', :m_kbns)
    Fixtures.create_fixtures('test/fixtures', :m_orgs)
    Fixtures.create_fixtures('test/fixtures', :m_apps)
    Fixtures.create_fixtures('test/fixtures', :m_app_auths)
    Fixtures.create_fixtures('test/fixtures', :m_notice_settings)
    Fixtures.create_fixtures('test/fixtures', :d_notice_heads)
    Fixtures.create_fixtures('test/fixtures', :d_notice_bodies)
    Fixtures.create_fixtures('test/fixtures', :d_notice_auths)
    Fixtures.create_fixtures('test/fixtures', :d_notice_indices)
    Fixtures.create_fixtures('test/fixtures', :d_notice_public_orgs)
#    Fixtures.create_fixtures('test/fixtures', :d_mail_configs)
    Fixtures.create_fixtures('test/fixtures', :d_addresses)
    Fixtures.create_fixtures('test/fixtures', :d_rss_trunks)
    Fixtures.create_fixtures('test/fixtures', :d_rss_readers)
    Fixtures.create_fixtures('test/fixtures', :d_cabinet_heads)
    Fixtures.create_fixtures('test/fixtures', :d_cabinet_indices)
    Fixtures.create_fixtures('test/fixtures', :d_cabinet_auths)
    Fixtures.create_fixtures('test/fixtures', :d_cabinet_bodies)
    Fixtures.create_fixtures('test/fixtures', :d_cabinet_public_orgs)
    Fixtures.create_fixtures('test/fixtures', :m_cabinet_settings)
    Fixtures.create_fixtures('test/fixtures', :d_blog_heads)
    Fixtures.create_fixtures('test/fixtures', :d_blog_bodies)
    Fixtures.create_fixtures('test/fixtures', :d_blog_tags)
    Fixtures.create_fixtures('test/fixtures', :d_blog_favorites)
    Fixtures.create_fixtures('test/fixtures', :m_blog_settings)
    Fixtures.create_fixtures('test/fixtures', :m_bbs_settings)
    Fixtures.create_fixtures('test/fixtures', :d_bbs_auths)
    Fixtures.create_fixtures('test/fixtures', :d_bbs_boards)
    Fixtures.create_fixtures('test/fixtures', :d_bbs_comments)
    Fixtures.create_fixtures('test/fixtures', :d_bbs_threads)
    Fixtures.create_fixtures('test/fixtures', :d_bulletin_bodies)
    Fixtures.create_fixtures('test/fixtures', :d_bulletin_heads)
    Fixtures.create_fixtures('test/fixtures', :m_projects)
    Fixtures.create_fixtures('test/fixtures', :m_project_users)
    Fixtures.create_fixtures('test/fixtures', :m_positions)
    Fixtures.create_fixtures('test/fixtures', :m_places)
    Fixtures.create_fixtures('test/fixtures', :m_facilities)
    Fixtures.create_fixtures('test/fixtures', :m_secretaries)
    Fixtures.create_fixtures('test/fixtures', :m_facilities)
    Fixtures.create_fixtures('test/fixtures', :m_facility_groups)
    Fixtures.create_fixtures('test/fixtures', :m_menus)
    Fixtures.create_fixtures('test/fixtures', :m_menu_auths)
    Fixtures.create_fixtures('test/fixtures', :d_bookmark_categories)
    Fixtures.create_fixtures('test/fixtures', :d_bookmarks)
    Fixtures.create_fixtures('test/fixtures', :m_companies)
    Fixtures.create_fixtures('test/fixtures', :m_calendars)
#    Fixtures.create_fixtures('test/fixtures', :m_ngwords)
#    Fixtures.create_fixtures('test/fixtures', :d_rulebook_heads)
#    Fixtures.create_fixtures('test/fixtures', :d_rulebook_bodies)
#    Fixtures.create_fixtures('test/fixtures', :d_rulebook_histories)
    Fixtures.create_fixtures('test/fixtures', :d_messages)
    Fixtures.create_fixtures('test/fixtures', :d_address_groups)
    Fixtures.create_fixtures('test/fixtures', :d_address_group_lists)
#    Fixtures.create_fixtures('test/fixtures', :d_questionnaire_heads)
#    Fixtures.create_fixtures('test/fixtures', :m_action_targets)
Fixtures.create_fixtures('test/fixtures', :d_reports)
Fixtures.create_fixtures('test/fixtures', :d_report_customers)
    Fixtures.create_fixtures('test/fixtures', :m_action_targets)
    Fixtures.create_fixtures('test/fixtures', :m_action_groups)
    Fixtures.create_fixtures('test/fixtures', :m_actions)
    Fixtures.create_fixtures('test/fixtures', :m_customers)
    Fixtures.create_fixtures('test/fixtures', :m_superiors)
    Fixtures.create_fixtures('test/fixtures', :m_workers)

  end

  def self.down

  end
end
